## PANDAS

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\aswak\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\aswak\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aswak\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aswak\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aswak\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aswak\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
import pandas as pd
data=pd.read_csv("x.csv")
data

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1.0,3,145,233.0,1,0,150.0,0,2.3,0,0.0,1,1
1,37,1.0,2,130,250.0,0,1,187.0,0,3.5,0,0.0,2,1
2,41,0.0,1,130,204.0,0,0,172.0,0,1.4,2,0.0,2,1
3,56,1.0,1,120,236.0,0,1,178.0,0,0.8,2,0.0,2,1
4,57,0.0,0,120,354.0,0,1,163.0,1,0.6,2,0.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0.0,0,140,241.0,0,1,123.0,1,0.2,1,0.0,3,0
299,45,1.0,3,110,264.0,0,1,132.0,0,1.2,1,0.0,3,0
300,68,1.0,0,144,193.0,1,1,141.0,0,3.4,1,2.0,3,0
301,57,1.0,0,130,131.0,0,1,115.0,1,1.2,1,1.0,3,0
302,57,0.0,1,130,236.0,0,0,174.0,0,0.0,1,1.0,2,0

In [6]:
data.head()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1.0,3,145,233.0,1,0,150.0,0,2.3,0,0.0,1,1
1,37,1.0,2,130,250.0,0,1,187.0,0,3.5,0,0.0,2,1
2,41,0.0,1,130,204.0,0,0,172.0,0,1.4,2,0.0,2,1
3,56,1.0,1,120,236.0,0,1,178.0,0,0.8,2,0.0,2,1
4,57,0.0,0,120,354.0,0,1,163.0,1,0.6,2,0.0,2,1

In [8]:
data.tail()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0.0,0,140,241.0,0,1,123.0,1,0.2,1,0.0,3,0
299,45,1.0,3,110,264.0,0,1,132.0,0,1.2,1,0.0,3,0
300,68,1.0,0,144,193.0,1,1,141.0,0,3.4,1,2.0,3,0
301,57,1.0,0,130,131.0,0,1,115.0,1,1.2,1,1.0,3,0
302,57,0.0,1,130,236.0,0,0,174.0,0,0.0,1,1.0,2,0

In [10]:
data.describe()

,age,gender,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,302.000000,303.000000,303.000000,299.000000,303.000000,303.000000,302.000000,303.000000,301.000000,303.000000,302.000000,303.000000,303.000000
mean,54.366337,0.682119,0.966997,131.623762,246.471572,0.148515,0.528053,149.705298,0.326733,1.037209,1.399340,0.731788,2.313531,0.544554
std,9.082101,0.466426,1.032052,17.538143,52.054067,0.356198,0.525860,22.920545,0.469794,1.164565,0.616226,1.023438,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,134.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.000000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   gender    302 non-null    float64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      299 non-null    float64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   302 non-null    float64
 8   exang     303 non-null    int64
 9   oldpeak   301 non-null    float64
 10  slope     303 non-null    int64
 11  ca        302 non-null    float64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(5), int64(9)
memory usage: 33.3 KB

In [14]:
a= data.isnull()
print(a)

       age  gender     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0    False   False  False     False  False  False    False    False  False
1    False   False  False     False  False  False    False    False  False
2    False   False  False     False  False  False    False    False  False
3    False   False  False     False  False  False    False    False  False
4    False   False  False     False  False  False    False    False  False
..     ...     ...    ...       ...    ...    ...      ...      ...    ...
298  False   False  False     False  False  False    False    False  False
299  False   False  False     False  False  False    False    False  False
300  False   False  False     False  False  False    False    False  False
301  False   False  False     False  False  False    False    False  False
302  False   False  False     False  False  False    False    False  False

     oldpeak  slope     ca   thal  target
0      False  False  False  False   False
1      False  False  False  False   False
2      False  False  False  False   False
3      False  False  False  False   False
4      False  False  False  False   False
..       ...    ...    ...    ...     ...
298    False  False  False  False   False
299    False  False  False  False   False
300    False  False  False  False   False
301    False  False  False  False   False
302    False  False  False  False   False

[303 rows x 14 columns]

In [18]:
a=data.isnull().sum()
print(a)

age         0
gender      1
cp          0
trestbps    0
chol        4
fbs         0
restecg     0
thalach     1
exang       0
oldpeak     2
slope       0
ca          1
thal        0
target      0
dtype: int64