In [9]:
import pandas as pd
data=pd.read_csv("x.csv marks.csv")
data

    Tamil  English  Maths  Science  Social Grade
0      86       36     39       36      53     D
1      49       40     48       37      82     D
2      95       88     61       90      37     B
3      55       38     43       93      54     D
4      58       88     49       36      58     D
5      37       97     76       36      88     C
6      56       52     85       88      67     C
7      87       78     97       35      58     B
8      36       68     86       53      70     C
9      64       96     38       36      72     C
10     72       48     57       87      59     C
11     36       82     49       78      52     D
12     98       49     77       66     100     B
13     94       96     63       66      88     A
14     55       74     70       89      69     B
15     67       87     47       90      95     B
16     92       58     66       51      75     C
17     56       60     93       72      67     C
18     83       94     62       58      67     B
19     93       75    100       45      48     B
20     76       63     76       50      55     C
21     94       49     79       93      82     B
22     49       79     96       37      54     C
23     96       99     91       54      42     B
24     96       43     40       93      41     C
25     81       35     62       70      51     D
26     96       42     62       53      67     C
27     85       97     78       53      82     B
28     89       45     64       54      93     C
29     98       42     96       86      56     B
30     37       69     96       67      64     C
31     85       69     35       74      72     C
32     41       67     61       73      85     C
33     55       39     96       35      88     C
34     73       75     37       45      42     D
35     52       62     61       91      61     C
36     38       41     43       84      61     D
37     94       46     96       57      55     C
38     48       68     71       65      64     C
39     43       67     85       76      62     C
40     87       82     78       41      98     B
41     36       57     58       50      95     D
42     94       96     93       94      82    A+
43     78       71     66       36      53     C
44     42       78     86       35      38     D
45     81       69     96       82      69     B
46     69       99     92       46      98     A
47     70       81     86       71      83     B
48     84       37     46       66      51     D
49     38       35     73       43      78     D

In [11]:
data.head()

   Tamil  English  Maths  Science  Social Grade
0     86       36     39       36      53     D
1     49       40     48       37      82     D
2     95       88     61       90      37     B
3     55       38     43       93      54     D
4     58       88     49       36      58     D

In [13]:
data.tail()

    Tamil  English  Maths  Science  Social Grade
45     81       69     96       82      69     B
46     69       99     92       46      98     A
47     70       81     86       71      83     B
48     84       37     46       66      51     D
49     38       35     73       43      78     D

In [15]:
data.describe()

           Tamil    English       Maths    Science      Social
count  50.000000  50.000000   50.000000  50.000000   50.000000
mean   69.480000  66.120000   70.100000  62.320000   67.620000
std    21.610882  20.591895   19.804401  20.263005   17.223489
min    36.000000  35.000000   35.000000  35.000000   37.000000
25%    49.750000  46.500000   57.250000  45.000000   54.250000
50%    72.500000  68.000000   70.500000  61.500000   67.000000
75%    88.500000  81.750000   86.000000  81.000000   82.000000
max    98.000000  99.000000  100.000000  94.000000  100.000000

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Tamil    50 non-null     int64
 1   English  50 non-null     int64
 2   Maths    50 non-null     int64
 3   Science  50 non-null     int64
 4   Social   50 non-null     int64
 5   Grade    50 non-null     object
dtypes: int64(5), object(1)
memory usage: 2.5+ KB

In [19]:
a=data.isnull()
print(a)

    Tamil  English  Maths  Science  Social  Grade
0   False    False  False    False   False  False
1   False    False  False    False   False  False
2   False    False  False    False   False  False
3   False    False  False    False   False  False
4   False    False  False    False   False  False
5   False    False  False    False   False  False
6   False    False  False    False   False  False
7   False    False  False    False   False  False
8   False    False  False    False   False  False
9   False    False  False    False   False  False
10  False    False  False    False   False  False
11  False    False  False    False   False  False
12  False    False  False    False   False  False
13  False    False  False    False   False  False
14  False    False  False    False   False  False
15  False    False  False    False   False  False
16  False    False  False    False   False  False
17  False    False  False    False   False  False
18  False    False  False    False   False  False
19  False    False  False    False   False  False
20  False    False  False    False   False  False
21  False    False  False    False   False  False
22  False    False  False    False   False  False
23  False    False  False    False   False  False
24  False    False  False    False   False  False
25  False    False  False    False   False  False
26  False    False  False    False   False  False
27  False    False  False    False   False  False
28  False    False  False    False   False  False
29  False    False  False    False   False  False
30  False    False  False    False   False  False
31  False    False  False    False   False  False
32  False    False  False    False   False  False
33  False    False  False    False   False  False
34  False    False  False    False   False  False
35  False    False  False    False   False  False
36  False    False  False    False   False  False
37  False    False  False    False   False  False
38  False    False  False    False   False  False
39  False    False  False    False   False  False
40  False    False  False    False   False  False
41  False    False  False    False   False  False
42  False    False  False    False   False  False
43  False    False  False    False   False  False
44  False    False  False    False   False  False
45  False    False  False    False   False  False
46  False    False  False    False   False  False
47  False    False  False    False   False  False
48  False    False  False    False   False  False
49  False    False  False    False   False  False

In [21]:
a=data.isnull().sum()
print(a)

Tamil      0
English    0
Maths      0
Science    0
Social     0
Grade      0
dtype: int64