In [7]:
import pandas as pd
data=pd.read_csv("x_missing.csv")
data

    Tamil  English  Maths  Science  Social Grade
0    86.0     36.0   39.0      NaN    53.0     D
1    49.0     40.0   48.0     37.0    82.0     D
2    95.0     88.0   61.0     90.0    37.0     B
3    55.0      NaN   43.0     93.0    54.0     D
4    58.0     88.0   49.0     36.0    58.0     D
5    37.0     97.0   76.0     36.0    88.0     C
6     NaN     52.0   85.0      NaN    67.0     C
7    87.0     78.0   97.0     35.0    58.0     B
8    36.0     68.0   86.0     53.0    70.0     C
9    64.0     96.0   38.0     36.0    72.0     C
10   72.0     48.0   57.0     87.0    59.0     C
11   36.0     82.0   49.0      NaN    52.0     D
12   98.0     49.0   77.0     66.0     NaN     B
13   94.0      NaN   63.0     66.0    88.0     A
14   55.0     74.0   70.0     89.0    69.0     B
15   67.0      NaN   47.0     90.0    95.0     B
16   92.0     58.0   66.0     51.0    75.0     C
17   56.0     60.0   93.0     72.0    67.0     C
18   83.0     94.0   62.0     58.0     NaN     B
19   93.0     75.0    NaN     45.0    48.0     B
20   76.0     63.0   76.0     50.0    55.0     C
21   94.0     49.0   79.0     93.0    82.0     B
22   49.0     79.0    NaN     37.0     NaN     C
23   96.0     99.0    NaN     54.0    42.0     B
24   96.0     43.0   40.0     93.0    41.0     C
25    NaN     35.0   62.0      NaN    51.0     D
26   96.0     42.0   62.0     53.0    67.0     C
27   85.0     97.0   78.0     53.0    82.0     B
28   89.0     45.0   64.0     54.0     NaN     C
29    NaN     42.0   96.0     86.0    56.0     B
30   37.0     69.0   96.0     67.0    64.0     C
31   85.0     69.0   35.0     74.0    72.0     C
32   41.0     67.0   61.0     73.0     NaN     C
33    NaN      NaN   96.0     35.0    88.0     C
34   73.0     75.0   37.0     45.0    42.0     D
35   52.0     62.0   61.0     91.0    61.0     C
36   38.0     41.0   43.0     84.0    61.0     D
37   94.0     46.0   96.0     57.0    55.0     C
38   48.0     68.0   71.0      NaN    64.0     C
39   43.0     67.0   85.0     76.0    62.0     C
40   87.0     82.0   78.0     41.0    98.0     B
41   36.0     57.0   58.0     50.0    95.0     D
42   94.0     96.0    NaN     94.0    82.0    A+
43   78.0     71.0   66.0     36.0    53.0     C
44   42.0     78.0   86.0     35.0    38.0     D
45   81.0     69.0   96.0     82.0    69.0     B
46   69.0     99.0   92.0     46.0    98.0     A
47    NaN     81.0    NaN     71.0    83.0     B
48   84.0     37.0   46.0     66.0    51.0     D
49   38.0      NaN   73.0     43.0    78.0     D

In [9]:
data.head()

   Tamil  English  Maths  Science  Social Grade
0   86.0     36.0   39.0      NaN    53.0     D
1   49.0     40.0   48.0     37.0    82.0     D
2   95.0     88.0   61.0     90.0    37.0     B
3   55.0      NaN   43.0     93.0    54.0     D
4   58.0     88.0   49.0     36.0    58.0     D

In [11]:
data.tail()

    Tamil  English  Maths  Science  Social Grade
45   81.0     69.0   96.0     82.0    69.0     B
46   69.0     99.0   92.0     46.0    98.0     A
47    NaN     81.0    NaN     71.0    83.0     B
48   84.0     37.0   46.0     66.0    51.0     D
49   38.0      NaN   73.0     43.0    78.0     D

In [13]:
data.describe()

           Tamil    English      Maths    Science     Social
count  45.000000  45.000000  45.000000  45.000000  45.000000
mean   69.200000  66.911111  67.533333  61.755556  66.266667
std    22.127318  19.613101  19.154397  20.471883  16.701116
min    36.000000  35.000000  35.000000  35.000000  37.000000
25%    49.000000  49.000000  49.000000  45.000000  54.000000
50%    73.000000  68.000000  66.000000  57.000000  64.000000
75%    89.000000  81.000000  85.000000  82.000000  82.000000
max    98.000000  99.000000  97.000000  94.000000  98.000000

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Tamil    45 non-null     float64
 1   English  45 non-null     float64
 2   Maths    45 non-null     float64
 3   Science  45 non-null     float64
 4   Social   45 non-null     float64
 5   Grade    50 non-null     object
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [17]:
a= data.isnull()
print(a)

    Tamil  English  Maths  Science  Social  Grade
0   False    False  False     True   False  False
1   False    False  False    False   False  False
2   False    False  False    False   False  False
3   False     True  False    False   False  False
4   False    False  False    False   False  False
5   False    False  False    False   False  False
6    True    False  False     True   False  False
7   False    False  False    False   False  False
8   False    False  False    False   False  False
9   False    False  False    False   False  False
10  False    False  False    False   False  False
11  False    False  False     True   False  False
12  False    False  False    False    True  False
13  False     True  False    False   False  False
14  False    False  False    False   False  False
15  False     True  False    False   False  False
16  False    False  False    False   False  False
17  False    False  False    False   False  False
18  False    False  False    False    True  False
19  False    False   True    False   False  False
20  False    False  False    False   False  False
21  False    False  False    False   False  False
22  False    False   True    False    True  False
23  False    False   True    False   False  False
24  False    False  False    False   False  False
25   True    False  False     True   False  False
26  False    False  False    False   False  False
27  False    False  False    False   False  False
28  False    False  False    False    True  False
29   True    False  False    False   False  False
30  False    False  False    False   False  False
31  False    False  False    False   False  False
32  False    False  False    False    True  False
33   True     True  False    False   False  False
34  False    False  False    False   False  False
35  False    False  False    False   False  False
36  False    False  False    False   False  False
37  False    False  False    False   False  False
38  False    False  False     True   False  False
39  False    False  False    False   False  False
40  False    False  False    False   False  False
41  False    False  False    False   False  False
42  False    False   True    False   False  False
43  False    False  False    False   False  False
44  False    False  False    False   False  False
45  False    False  False    False   False  False
46  False    False  False    False   False  False
47   True    False   True    False   False  False
48  False    False  False    False   False  False
49  False     True  False    False   False  False

In [19]:
a1=data.isnull().sum()
print(a1)

Tamil      5
English    5
Maths      5
Science    5
Social     5
Grade      0
dtype: int64